          name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Display Name'
        required: true
        default: 'Wrappr App'
      app_url:
        description: 'Website Target URL'
        required: true
        default: 'https://google.com'

jobs:
  build-apk:
    name: Generate Flutter Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: 'ideabroofficial/wrappr-template-code'
          token: ${{ secrets.TEMPLATE_PAT }}
          ref: 'main'

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:"
          cache-path: "${{ runner.tool_cache }}/flutter"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release

      - name: Upload Generated APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
